version: "3.7"

services:
  survey_db:
    image: postgres:13.4-alpine
    restart: always
    container_name: survey_db
    env_file:
      - ./.env
    networks:
      - survey_network
    expose:
      - 5432
    ports:
      - "5440:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  survey_server:
    build: ./
    restart: always
    container_name: survey_api
    command: sh -c "uvicorn api.main:app --host=0.0.0.0 --reload"
    working_dir: /app
    networks:
      - survey_network
    env_file:
      - ./.env
    volumes:
      - ./:/app:cached
    expose:
      - 8000
    ports:
      - "8081:8000"
    depends_on:
      - survey_db

  redis:
    image: redis:alpine
    container_name: survey_redis
    networks:
      - survey_network
    expose:
      - 6379

  client:
    build: ./client
    restart: always
    container_name: survey_client
    command: sh -c "yarn install && yarn serve"
    working_dir: /app/client
    volumes:
      - ./client:/app/client:cached
    ports:
      - "8082:8080"

networks:
  survey_network:
    name: nginx-api-gateway-network
