version: '3.7'

services:
  log_db:
    image: postgres:13.4-alpine
    restart: always
    container_name: log_service_db
    env_file:
      - ./.env
    networks:
      - log_service_network
    expose:
      - 5432
    ports:
    - '5440:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  log_server:
    build: ./
    restart: always
    container_name: log_service_api
    command: sh -c "uvicorn api.main:app --host=0.0.0.0 --reload"
    working_dir: /app
    networks:
      - log_service_network
    env_file:
      - ./.env
    volumes:
      - ./:/app:cached
    expose:
      - 8000
    ports:
      - '8081:8000'
    depends_on:
      - log_db

  redis:
    image: redis:alpine
    container_name: log_redis
    networks:
      - log_service_network
    expose:
      - 6379

networks:
  log_service_network:
    name: nginx-api-gateway-network
